"""Integration tests for local tool availability vs project configuration.

Validates that project configuration and local tool availability are
reported separately and that skip-validation paths work correctly (US3).
"""

from pathlib import Path

import pytest

pytestmark = pytest.mark.integration


class TestValidationSummary:
    def test_configured_assistants_are_detectable(self, monkeypatch, tmp_path: Path):
        """After initialization, detect_configured_assistants must see configured tools."""
        resource_root = tmp_path / "resource"
        from fixtures.ai_tools_support import make_resource_with_skills

        make_resource_with_skills(resource_root)
        monkeypatch.setattr("specify_cli.get_resource_path", lambda: resource_root)

        from specify_cli import copy_local_templates, detect_configured_assistants

        project = tmp_path / "detect"
        copy_local_templates(project, "copilot", "sh")

        configured = detect_configured_assistants(project)
        assert "copilot" in configured, "copilot not detected after init"

    def test_multiple_configured_assistants_detected(self, monkeypatch, tmp_path: Path):
        """After adding multiple assistants, all are detected."""
        resource_root = tmp_path / "resource"
        from fixtures.ai_tools_support import make_resource_with_skills

        make_resource_with_skills(resource_root)
        monkeypatch.setattr("specify_cli.get_resource_path", lambda: resource_root)

        from specify_cli import copy_local_templates, detect_configured_assistants

        project = tmp_path / "multi-detect"
        copy_local_templates(project, "copilot", "sh")
        copy_local_templates(project, "claude", "sh", is_current_dir=True)
        copy_local_templates(project, "qwen", "sh", is_current_dir=True)

        configured = detect_configured_assistants(project)
        for expected in ["copilot", "claude", "qwen"]:
            assert expected in configured, f"{expected} not detected"

    def test_empty_project_returns_no_assistants(self, tmp_path: Path):
        """An empty project should report no configured assistants."""
        from specify_cli import detect_configured_assistants

        configured = detect_configured_assistants(tmp_path)
        assert configured == [], f"Unexpected assistants: {configured}"

    def test_core_assets_detectable_in_multi_assistant_project(
        self, monkeypatch, tmp_path: Path
    ):
        """Core asset detection works correctly in multi-assistant workspace."""
        resource_root = tmp_path / "resource"
        from fixtures.ai_tools_support import make_resource_with_skills

        make_resource_with_skills(resource_root)
        monkeypatch.setattr("specify_cli.get_resource_path", lambda: resource_root)

        from specify_cli import (
            copy_local_templates,
            core_asset_relpaths,
            detect_initialized_core_assets,
        )

        project = tmp_path / "core-detect"
        copy_local_templates(project, "copilot", "sh")
        copy_local_templates(project, "qwen", "sh", is_current_dir=True)

        initialized = detect_initialized_core_assets(project)
        all_core = core_asset_relpaths()

        # After full init, most core assets should be present
        # Note: .specify/instructions.md is generated by /speckit.instructions, not init
        init_core = [p for p in all_core if p != ".specify/instructions.md"]
        for path in init_core:
            assert path in initialized, f"Core asset {path} not detected"
