"""Contract test: the tools discovery-inventory ownership claim.

Guards the correction recorded in feature 050's review (finding F8). Seven
surfaces claimed `.specify/memory/tools.md` was "the discovery inventory
regenerated by refresh-tools.sh". That was never true: the script writes nothing
and exits 1 without a source flag, nothing in the repo writes that file, and the
file is a hand-maintained MCP-server index whose three enumeration sections have
held only a one-line description each since the revision that added it.

The claim survived because it is prose *about* a mechanism and no test asserted
the mechanism. This file is that missing assertion — the general shape is: when a
document names a path as machine-generated, some script must actually write it.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

OWNER = ROOT / "shared" / "definitions" / "tool-definitions.md"
GENERATOR = ROOT / "scripts" / "bash" / "generate-instructions.sh"
REFRESH = ROOT / "scripts" / "bash" / "refresh-tools.sh"

# Every surface that used to carry the false claim. All must now point at the owner.
SURFACES = [
    "shared/definitions/tool-definitions.md",
    "templates/instructions-template.md",
    "templates/tools.md",
    "templates/commands/tools.md",
    "skills/create-tools/SKILL.md",
    "skills/improve-tools/SKILL.md",
]

INVENTORIES = ".specify/tools/{system,shell,project}.json"
MCP_INDEX = ".specify/memory/tools.md"

# The false claim, in the shape it actually appeared: tools.md described as the
# discovery inventory AND regenerated by refresh-tools.sh, in one sentence.
FALSE_CLAIM = re.compile(
    r"memory/tools\.md[^\n]{0,120}discovery inventory[^\n]{0,80}regenerated by[^\n]{0,40}refresh-tools\.sh"
)


def read(rel: str) -> str:
    p = ROOT / rel
    assert p.is_file(), f"missing surface: {rel}"
    return p.read_text(encoding="utf-8")


# --- the false claim is gone from every shipped surface ---


def test_no_surface_claims_tools_md_is_regenerated():
    offenders = []
    for rel in SURFACES:
        for lineno, line in enumerate(read(rel).splitlines(), 1):
            if FALSE_CLAIM.search(line):
                offenders.append(f"{rel}:{lineno}")
    assert not offenders, (
        "the false claim is back: these lines describe .specify/memory/tools.md as the "
        f"discovery inventory regenerated by refresh-tools.sh -> {offenders}. "
        "Nothing writes that file; see test_refresh_tools_writes_no_file below."
    )


def test_no_surface_claims_it_anywhere_in_the_repo():
    """Sweep the shipped trees, not just the known six, so a new copy cannot appear."""
    offenders = []
    for base in ("shared", "templates", "skills", "docs"):
        d = ROOT / base
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*.md")):
            relp = p.relative_to(ROOT)
            if any(part in relp.parts for part in (".specify", "node_modules", "__pycache__")):
                continue
            rel = relp.as_posix()
            for lineno, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
                if FALSE_CLAIM.search(line):
                    offenders.append(f"{rel}:{lineno}")
    assert not offenders, f"false claim present in shipped docs: {offenders}"


# --- the real mechanism is what the docs now say ---


def test_owner_names_the_real_inventories():
    body = read("shared/definitions/tool-definitions.md")
    assert INVENTORIES in body, (
        f"the owner must name the real generated inventories ({INVENTORIES})"
    )
    assert "generate-instructions.sh" in body, (
        "the owner must name the script that actually writes the inventories"
    )


def test_owner_states_tools_md_is_not_generated():
    body = read("shared/definitions/tool-definitions.md")
    assert MCP_INDEX in body
    assert re.search(r"hand-maintained", body), (
        "the owner must state that tools.md is hand-maintained, or the ambiguity returns"
    )
    assert "MCP" in body, "the owner must say what tools.md actually indexes"


def test_every_surface_points_at_the_owner():
    """Pointer shape, not content shape: each copy must reach the owner by path.

    The owner itself is excluded — it cannot point at itself — and is instead
    required to declare its own authority, which is the property that matters there.
    """
    copies = [rel for rel in SURFACES if rel != "shared/definitions/tool-definitions.md"]
    missing = [rel for rel in copies if "tool-definitions.md" not in read(rel)]
    assert not missing, (
        f"these surfaces discuss the inventories without pointing at the owner: {missing}. "
        "A restated fact in six places is what let the false claim survive."
    )
    owner = read("shared/definitions/tool-definitions.md")
    assert re.search(r"(?i)authoritative|single source|owned by", owner), (
        "the owner document must declare its own authority"
    )


def test_generator_actually_writes_the_three_inventories():
    body = read("scripts/bash/generate-instructions.sh")
    for source, target in (
        ("--system", "system.json"),
        ("--shell", "shell.json"),
        ("--project", "project.json"),
    ):
        assert re.search(
            rf"refresh-tools\.sh\"?\s+{re.escape(source)}\s+--json\s*>\s*\"\$TOOLS_DIR/{re.escape(target)}\"",
            body,
        ), f"generate-instructions.sh no longer redirects {source} into {target}"


def test_refresh_tools_requires_a_source_flag_and_says_why():
    """The trap that made DoD-8 unsatisfiable: bare --json is a usage error.

    The message must name the requirement AND correct the inventory misconception
    at the point of failure — that is what stops the next agent from repeating it.
    """
    proc = subprocess.run(
        ["bash", str(REFRESH), "--json"], cwd=ROOT, capture_output=True, text=True
    )
    assert proc.returncode != 0, (
        "refresh-tools.sh --json now succeeds standalone; if it also writes "
        ".specify/memory/tools.md, the owner doc must be updated to say so"
    )
    usage = proc.stderr
    assert "SOURCE flag" in usage, "the usage text must say a source flag is required"
    assert "memory/tools.md" in usage and "hand-maintained" in usage, (
        "the usage text must correct the misconception at the point of failure"
    )


# A mention of a path is not a write to it: refresh-tools.sh now documents that it
# does NOT produce .specify/memory/tools.md, so these assert on write operations.
WRITE_PATTERNS = (
    r">\s*[^\n]*memory/tools\.md",          # shell redirection into it
    r"tee\s+[^\n]*memory/tools\.md",        # tee into it
    r"memory/tools\.md[^\n]*['\"][wa]",     # python open(..., "w"/"a")
    r"write_text[^\n]*memory/tools\.md",
    r"memory/tools\.md[^\n]*write_text",
)


def _write_offenders(text: str) -> list:
    return [p for p in WRITE_PATTERNS if re.search(p, text)]


def test_no_script_writes_the_mcp_index():
    """Nothing in scripts/ or src/ WRITES it (mentioning it to warn is fine)."""
    offenders = []
    for base in ("scripts", "src"):
        d = ROOT / base
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*")):
            if p.suffix not in (".py", ".sh") or not p.is_file():
                continue
            text = p.read_text(encoding="utf-8", errors="replace")
            hits = _write_offenders(text)
            if hits:
                offenders.append(f"{p.relative_to(ROOT).as_posix()} {hits}")
            # A fragment-built path would evade every literal pattern above.
            if re.search(r'["\']tools["\']\s*\+\s*["\']\.md', text):
                offenders.append(f"{p.relative_to(ROOT).as_posix()} fragment-built path")
    assert not offenders, (
        "these scripts WRITE the MCP index; if that is now intentional, the owner "
        f"doc's 'hand-maintained' claim is stale: {offenders}"
    )


def test_mention_without_write_is_allowed():
    """Guard the guard: the check above must not regress into a substring ban."""
    assert not _write_offenders(
        "Note: .specify/memory/tools.md is NOT produced here — it is hand-maintained."
    ), "a warning that mentions the path must not be classified as a write"
    assert _write_offenders('cat > "$ROOT/.specify/memory/tools.md"'), (
        "an actual redirection into the path must be classified as a write"
    )
